gpio -g mode 3 output
gpio -g write 3 0
gpio -g mode 2 output
gpio -g write 2 0
gpio -g mode 25 output
gpio -g write 25 0
gpio -g mode 24 output
gpio -g write 24 0
gpio -g mode 7 output
gpio -g write 7 0
gpio -g mode 8 output
gpio -g write 8 0
gpio -g mode 6 output
gpio -g write 6 0
gpio -g mode 5 output
gpio -g write 5 0
gpio -g mode 22 output
gpio -g write 22 0
gpio -g mode 10 output
gpio -g write 10 0
